version: '3'

services:
  app:
    image: front-interconectados-vite:latest
    container_name: front-interconectados-vite-app-1
    restart: always
    ports:
      - "5173:5173"
    networks:
      - frontend

  nginx:
    image: nginx:latest
    container_name: front-interconectados-vite-nginx-1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - front-interconectados-vite_certbot_www:/var/www/certbot
      - front-interconectados-vite_certbot_conf:/etc/letsencrypt
    networks:
      - frontend

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: --interval 300 --cleanup --label-enable --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

networks:
  frontend:
    external: true

volumes:
  front-interconectados-vite_certbot_www:
  front-interconectados-vite_certbot_conf:
