version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: front-interconectados-vite:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nginx-proxy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.temp.conf:/etc/nginx/nginx.conf  # Cambia a nginx.temp.conf inicialmente
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - nginx-proxy

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while ! curl -s http://nginx/.well-known/acme-challenge/; do sleep 1; done; certbot certonly --webroot -w /var/www/certbot -m interconectados.sa@gmail.com --agree-tos --no-eff-email -d interconectados.duckdns.org --staging --force-renewal; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nginx-proxy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - default

volumes:
  certbot_conf:
  certbot_www:

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
  default:
    external: false
