const questions = [
  {
    id: 21,
    text: "¿cuál fué tu mejor cumpleaños?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 22,
    text: "¿cúal es tu lunar favorito?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  { id: 23, text: "¿con qué soñas?", category: "todxs", likes: 0, dislikes: 0 },
  {
    id: 24,
    text: "¿cuál el viaje más emocionante que has vivido?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 25,
    text: "¿Qué aventura te gustaría emprender si no tuvieras ninguna limitación?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 26,
    text: "¿Qué recuerdo de tu infancia siempre te hace sonreír?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 27,
    text: "¿Cómo te gustaría ser recordado?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 28,
    text: "¿Qué área de tu vida sientes que necesita más crecimiento?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 29,
    text: "¿Cuál ha sido una lección importante que has aprendido sobre la honestidad?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 210,
    text: "¿Qué película siempre te hace reír sin importar cuántas veces la veas?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 211,
    text: "¿cuál es tu aroma favorito?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 212,
    text: "¿Cuál ha sido una experiencia reciente que te ha dejado un gran aprendizaje?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 213,
    text: "¿cuál es tu día favorito del año?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 214,
    text: "¿Cuál es una tradición que te gustaría eliminar para siempre?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 215,
    text: "¿Qué importancia tienen para ti las raíces familiares?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 216,
    text: "¿Cómo experimentas y expresas el amor en tu familia?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 217,
    text: "¿Cómo proteges a los que amas?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 218,
    text: "¿cuál es tu top 3 de musica?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 219,
    text: "¿Qué hace que un lugar se sienta como tu hogar?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 220,
    text: "¿cuál es tu género musical favorito?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 221,
    text: "¿Cuál es un sacrificio que has visto hacer a un ser querido?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 222,
    text: "¿Cuál es tu recuerdo favorito con tus hermanos?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 223,
    text: "¿en qué piensan las plantas?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 224,
    text: "¿cuál fué tu última caída?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 225,
    text: "¿Qué es la intimidad en una relación?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 226,
    text: "¿cuál fué la desición más difícil que tuviste que tomar?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 227,
    text: "¿cuál fué el último cambio que hiciste en tu vida?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 228,
    text: "¿Qué sueñas para tu futuro?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 229,
    text: "¿qué hecho hizo que te cambie la vida?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 230,
    text: "¿cuál fué la mejor desición que tomaste en la vida?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 231,
    text: "¿Qué significa la atracción para ti?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 232,
    text: "¿qué disfrutas hacer en tu estación favorita del año?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 233,
    text: "¿qué te gusta hacer antes de dormir?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 234,
    text: "¿Cuál es un momento en que te sentiste completamente libre?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 235,
    text: "¿qué es lo primero que haces cuando te levantas?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 236,
    text: "¿Cómo te motivas para alcanzar tus metas?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 237,
    text: "¿cuáles son los 3 valores mas importantes para vos?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 238,
    text: "¿cómo te imaginás dentro de 5 años?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 239,
    text: "¿Qué lecciones has aprendido de tus mayores desafíos?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 240,
    text: "¿qué te preocupa del futuro?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 241,
    text: "¿Cómo te sientes cuando estás solo?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 242,
    text: "¿cuál fué tu mayor logro?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 243,
    text: "¿cuál fué tu mayor fracaso?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 244,
    text: "¿Qué te gustaría descubrir sobre el mundo?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 245,
    text: "¿qué te gustaría aprender?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 246,
    text: "¿Cuál sientes que es tu propósito en la vida?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 247,
    text: "¿cuál es tu mayor miedo?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 248,
    text: "¿qué te da tranquilidad?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 249,
    text: "¿Qué cambios te gustaría ver en el futuro?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 250,
    text: "¿cuál es tu mayor virtud?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 251,
    text: "¿cuál es tu mayor defecto?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 252,
    text: "¿Qué cosas pequeñas te hacen feliz en el día a día?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 253,
    text: "¿cómo te describirías en una frase?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 254,
    text: "¿Qué despierta tu curiosidad actualmente?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 255,
    text: "¿qué habilidad te gustaría tener?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 256,
    text: "¿Qué significado tienen los sueños en tu vida?",
    category: "todxs",
    likes: 0,
    dislikes: 0,
  },
  //AMIGOS
  {
    id: 338,
    text: "¿cómo te imaginás a este grupo dentro de 5 años?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 339,
    text: "¿Cuál es la cosa más loca que harías solo porque un amigo te lo pidió?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 340,
    text: "Si pudieras planear una aventura espontánea con tus amigos ahora mismo, ¿a dónde irían y qué harían?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 341,
    text: "¿Cuál fue el momento más inesperado que terminó siendo un gran recuerdo con tus amigos?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 342,
    text: "Si pudieras vivir durante 1 año en cualquier parte del mundo ¿dónde sería?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 343,
    text: "¿Cuál ha sido el cambio más sorprendente que has visto en un amigo?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 344,
    text: "¿Cuál es la lección más importante que un amigo te ha enseñado?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 345,
    text: "¿Qué no negociarías?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 346,
    text: "¿Qué es lo más loco que te ha pasado por ser honesto con un amigo?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 347,
    text: "¿quién en tu vida te inspira a ser mejor?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 350,
    text: "¿Cómo te gustaría ser recordado por tus amigos?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 351,
    text: "¿qué te sorprende de vos mismo ultimamente?",
    category: "amigos",
    likes: 0,
    dislikes: 0,
  },

  //FAMILIA
  {
    id: 414,
    text: "Si tuvieras que elegir 2 discos/canciones que te vuelen la cabeza, ¿cuáles serían?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 415,
    text: "¿qué te entretiene?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 416,
    text: "¿cómo ves el mundo/planeta/civilización en mil años?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 417,
    text: 'Si te digo "aire" ¿en qué pensas?',
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 418,
    text: "¿qué significa para vos el vacío/la nada?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 419,
    text: '¿qué significa para vos la palabra "religión"?',
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 420,
    text: "Si no fuese en el planeta tierra ¿dónde te gustaría existir?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 421,
    text: "¿cuál es tu animal favorito?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 422,
    text: "¿en qué animal te gustaría reencarnar?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 423,
    text: "¿en qué piensan las plantas?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 424,
    text: "¿cuál fué tu última caída?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 425,
    text: "¿cuándo fué la última vez que te caíste?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 426,
    text: "¿cuál fué la desición más difícil que tuviste que tomar?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 427,
    text: "¿cuál fué el último cambio que hiciste en tu vida?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 428,
    text: "¿qué impulsó el último cambio que hiciste en tu vida?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 429,
    text: "¿qué hecho hizo que te cambie la vida?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 430,
    text: "¿cuál fué la mejor desición que tomaste en la vida?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 431,
    text: "¿cuál fué la desición más fácil de tomar?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 432,
    text: "¿qué disfrutas hacer en tu estación favorita del año?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 433,
    text: "¿qué te gusta hacer antes de dormir?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 434,
    text: "¿qué tenes que hacer si o si antes de ir a dormir?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 435,
    text: "¿qué es lo primero que haces cuando te levantas?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 436,
    text: "¿qué te gusta hacer cuando te despertas?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 437,
    text: "¿cuáles son los 3 valores mas importantes para vos?",
    category: "familia",
    likes: 0,
    dislikes: 0,
  },
  //CITA
  {
    id: 555,
    text: "¿qué experiencia te enseñó mucho sobre el amor?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 349,
    text: "¿cuál es nuestro mayor desafío actual?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 371,
    text: "¿Qué significa el compromiso para ti en una relación?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 570,
    text: "¿Qué crees que hace que la atracción sea duradera en una relación?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 352,
    text: "¿qué actividad te ayuda a encontrar la paz?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 6012,
    text: "¿Cuál es la primera cosa que notaste de mí cuando nos conocimos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 559,
    text: "¿Qué te gustaría que este vínculo aporte en tu vida?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 560,
    text: "¿Qué experiencia nueva te gustaría que compartiéramos juntos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 561,
    text: "¿Cómo te imaginas un día perfecto juntos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 562,
    text: "¿Cuál es la cosa más importante que te gustaría que construyéramos juntos en nuestra relación?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 563,
    text: "¿Qué crees que fortalece más nuestro vínculo?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 564,
    text: "¿Qué actividad nueva te gustaría que probáramos juntos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 565,
    text: "¿Qué crees que es lo más curioso que te hace único?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 566,
    text: "Si pudiéramos viajar a cualquier lugar del mundo mañana, ¿a dónde iríamos y qué haríamos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 566,
    text: "¿Qué aventura te gustaría que planificáramos juntos para el próximo año?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 567,
    text: "¿Qué recuerdo te hace sonreír cada vez que lo piensas?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 568,
    text: "¿Qué actividad diaria te hace sentir más conectado?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 569,
    text: "¿Cuál es un sueño que crees que podemos alcanzar juntos y cómo lo haríamos?",
    category: "cita",
    likes: 0,
    dislikes: 0,
  },

  //SOLITARIO
  {
    id: 353,
    text: "¿Qué tipo de persona sos?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 6013,
    text: "¿Qué querés en este momento de tu vida?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 500,
    text: "¿Cómo describirías tu estado emocional actual en tres palabras?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 501,
    text: "¿Qué es lo que más te gusta de tu vida en este momento?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 502,
    text: "¿Cuáles son los principales desafíos que enfrentas actualmente?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 503,
    text: "¿Qué hábitos diarios te hacen sentir bien con vos mismo?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 504,
    text: "¿Cómo manejas el estrés?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 505,
    text: "¿Dónde te gustaría verte en un año?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 506,
    text: "¿Cuál es una meta a largo plazo que te emociona y por qué?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 507,
    text: "¿Qué cambios pequeños podrías hacer hoy para acercarte a tu estado deseado?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 508,
    text: "¿Qué estás dispuesto a dejar para conseguir tus metas?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 509,
    text: "¿Cómo sería un día perfecto para vos?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 510,
    text: "¿Cómo te defines cuando estás en tu mejor versión?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 511,
    text: "¿Quién eres cuando nadie te está observando?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 512,
    text: "¿Qué partes de tu identidad te gustaría explorar más?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 513,
    text: "¿Cuál es el logro del que te sientes más orgulloso y por qué?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 514,
    text: "¿Qué es algo que siempre has querido lograr pero aún no has comenzado?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 515,
    text: "¿Qué es algo que te gustaría intentar?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 516,
    text: "¿Qué intentarías si no tuvieras miedo?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 517,
    text: "¿Qué te gustaría agradecerte a ti mismo?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 518,
    text: "¿Cuál ha sido una lección importante que has aprendido este último tiempo?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 519,
    text: "¿Qué significa ser auténtico para ti?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 520,
    text: "¿Por qué cosas estás agradecido en este momento?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 521,
    text: "¿Cómo practicas la gratitud?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 522,
    text: "¿Qué pequeñas cosas en tu vida te traen alegría?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 523,
    text: "¿Qué te da esperanza para el futuro?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 524,
    text: "¿Qué te inspira a seguir soñando en grande?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
  {
    id: 525,
    text: "¿Cómo puedes empezar a trabajar hacia uno de tus grandes sueños hoy mismo?",
    category: "solo",
    likes: 0,
    dislikes: 0,
  },
];

export default questions;
