- name: Configurar Nginx con SSL
  hosts: webservers
  become: yes

  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Crear directorio para certbot
      file:
        path: /var/www/certbot
        state: directory

    - name: Crear archivo de configuración de Nginx para SSL
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                      autoindex on;  # Permitir el listado del directorio
                  }

                  location / {
                      proxy_pass http://front-interconectados-vite-app-1:5173;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }
              }

              server {
                  listen 443 ssl;
                  server_name interconectados.duckdns.org;

                  ssl_certificate /etc/letsencrypt/live/interconectados.duckdns.org/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/interconectados.duckdns.org/privkey.pem;

                  ssl_protocols TLSv1.2 TLSv1.3;
                  ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
                  ssl_prefer_server_ciphers on;
                  ssl_session_cache shared:SSL:10m;

                  location / {
                      proxy_pass http://front-interconectados-vite-app-1:5173;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                  }
              }
          }

    - name: Recargar Nginx para aplicar cambios
      systemd:
        name: nginx
        state: reloaded
