---
- name: Setup Front Interconectados
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/interconectados/front-interconectados-vite/certbot
        - /opt/interconectados/front-interconectados-vite/certbot/conf
        - /opt/interconectados/front-interconectados-vite/certbot/www
        - /opt/interconectados/front-interconectados-vite/certbot/www/.well-known/acme-challenge

    - name: Check if docker-compose.yml exists
      stat:
        path: /opt/interconectados/front-interconectados-vite/docker-compose.yml
      register: docker_compose_file

    - name: Create docker-compose.yml if not exists
      copy:
        dest: /opt/interconectados/front-interconectados-vite/docker-compose.yml
        content: |
          version: '3'

          services:
            app:
              image: front-interconectados-vite:latest
              container_name: front-interconectados-vite-app-1
              restart: always
              ports:
                - "3000:3000"
              networks:
                - default

            nginx:
              image: nginx:latest
              container_name: front-interconectados-vite-nginx-1
              restart: always
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf
                - front-interconectados-vite_certbot_www:/var/www/certbot
                - front-interconectados-vite_certbot_conf:/etc/letsencrypt
              networks:
                - default

            certbot:
              image: front-interconectados-vite_certbot
              container_name: front-interconectados-vite-certbot-1
              entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait \$${!}; certbot renew; done"
              volumes:
                - front-interconectados-vite_certbot_www:/var/www/certbot
                - front-interconectados-vite_certbot_conf:/etc/letsencrypt
              networks:
                - default

            watchtower:
              image: containrrr/watchtower
              container_name: watchtower
              restart: always
              command: --interval 300 --cleanup --label-enable --include-restarting
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
              networks:
                - default

          networks:
            default:
              external:
                name: nginx-proxy

          volumes:
            front-interconectados-vite_certbot_www:
            front-interconectados-vite_certbot_conf:
      when: not docker_compose_file.stat.exists

    - name: Check if nginx.conf is a file
      stat:
        path: /opt/interconectados/front-interconectados-vite/nginx.conf
      register: nginx_conf_file

    - name: Remove nginx.conf if it is a directory
      file:
        path: /opt/interconectados/front-interconectados-vite/nginx.conf
        state: absent
      when: nginx_conf_file.stat.isdir is defined and nginx_conf_file.stat.isdir

    - name: Create nginx.conf if not exists
      copy:
        dest: /opt/interconectados/front-interconectados-vite/nginx.conf
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                      autoindex on;  # Agregado para permitir el listado del directorio
                  }

                  location / {
                      return 200 'Temporary Nginx Server';
                  }
              }
          }
      when: not nginx_conf_file.stat.exists

    - name: Create nginx.temp.conf
      copy:
        dest: /opt/interconectados/front-interconectados-vite/nginx.temp.conf
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                      autoindex on;  # Agregado para permitir el listado del directorio
                  }

                  location / {
                      return 200 'Temporary Nginx Server';
                  }
              }
          }

    - name: Create test file for Certbot validation
      copy:
        dest: /opt/interconectados/front-interconectados-vite/certbot/www/.well-known/acme-challenge/test.txt
        content: "test"

    - name: Build Certbot Docker image
      command: docker build -f Dockerfile.certbot -t front-interconectados-vite_certbot .
      args:
        chdir: /opt/interconectados/front-interconectados-vite

    - name: Start Docker Compose with temporary Nginx configuration
      command: docker-compose -f /opt/interconectados/front-interconectados-vite/docker-compose.yml up -d
      args:
        chdir: /opt/interconectados/front-interconectados-vite

    - name: Wait for services to start
      pause:
        seconds: 10

    - name: Verify test file in Nginx container
      command: docker exec front-interconectados-vite-nginx-1 ls /var/www/certbot/.well-known/acme-challenge/test.txt
      register: verify_test_file
      until: verify_test_file.rc == 0
      retries: 3
      delay: 10

    - name: Run Certbot to obtain SSL certificates
      command: docker-compose run certbot certonly --webroot -w /var/www/certbot -m interconectados.sa@gmail.com --agree-tos --no-eff-email -d interconectados.duckdns.org --force-renewal
      args:
        chdir: /opt/interconectados/front-interconectados-vite
      register: certbot_result

    - name: Debug Certbot result
      debug:
        var: certbot_result

    - name: Wait for Certbot to complete
      command: docker ps -a | grep certbot | grep Exit
      register: certbot_status
      until: certbot_status.stdout != ""
      retries: 3
      delay: 10
      ignore_errors: true

    - name: Stop Docker Compose
      command: docker-compose down
      args:
        chdir: /opt/interconectados/front-interconectados-vite

    - name: Update nginx.conf with the final configuration
      copy:
        dest: /opt/interconectados/front-interconectados-vite/nginx.conf
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                  }

                  location / {
                      return 301 https://$host$request_uri;
                  }
              }

              server {
                  listen 443 ssl;
                  server_name interconectados.duckdns.org;

                  ssl_certificate /etc/letsencrypt/live/interconectados.duckdns.org/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/interconectados.duckdns.org/privkey.pem;

                  location / {
                      proxy_pass http://front-interconectados-vite-app-1:3000;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                  }
              }
          }

    - name: Start Docker Compose with final Nginx configuration
      command: docker-compose up -d
      args:
        chdir: /opt/interconectados/front-interconectados-vite
