---
- name: Setup Front Interconectados
  hosts: localhost
  become: true
  vars:
    workdir: /opt/interconectados/front-interconectados-vite
    docker_compose_file: "{{ workdir }}/docker-compose.yml"
    nginx_conf_file: "{{ workdir }}/nginx.conf"
    nginx_temp_conf_file: "{{ workdir }}/nginx.temp.conf"
    certbot_dir: "{{ workdir }}/certbot"
    certbot_conf_dir: "{{ certbot_dir }}/conf"
    certbot_www_dir: "{{ certbot_dir }}/www"
    challenge_dir: "{{ certbot_www_dir }}/.well-known/acme-challenge"
    dockerfile_certbot: "{{ workdir }}/Dockerfile.certbot"

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ certbot_dir }}"
        - "{{ certbot_conf_dir }}"
        - "{{ certbot_www_dir }}"
        - "{{ challenge_dir }}"

    - name: Check if docker-compose.yml exists
      stat:
        path: "{{ docker_compose_file }}"
      register: docker_compose_file

    - name: Create docker-compose.yml if not exists
      copy:
        dest: "{{ docker_compose_file }}"
        content: |
          version: '3'

          services:
            app:
              image: front-interconectados-vite:latest
              container_name: front-interconectados-vite-app-1
              restart: always
              ports:
                - "3000:3000"
              networks:
                - default

            nginx:
              image: nginx:latest
              container_name: front-interconectados-vite-nginx-1
              restart: always
              ports:
                - "80:80"
                - "443:443"
              volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf
                - front-interconectados-vite_certbot_www:/var/www/certbot
                - front-interconectados-vite_certbot_conf:/etc/letsencrypt
              networks:
                - default

            certbot:
              image: front-interconectados-vite_certbot
              container_name: front-interconectados-vite-certbot-1
              entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait \$${!}; certbot renew; done"
              volumes:
                - front-interconectados-vite_certbot_www:/var/www/certbot
                - front-interconectados-vite_certbot_conf:/etc/letsencrypt
              networks:
                - default

            watchtower:
              image: containrrr/watchtower
              container_name: watchtower
              restart: always
              command: --interval 300 --cleanup --label-enable --include-restarting
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
              networks:
                - default

          networks:
            default:
              name: nginx-proxy

          volumes:
            front-interconectados-vite_certbot_www:
            front-interconectados-vite_certbot_conf:
      when: not docker_compose_file.stat.exists

    - name: Check if nginx.conf is a file
      stat:
        path: "{{ nginx_conf_file }}"
      register: nginx_conf_stat

    - name: Remove nginx.conf if it is a directory
      file:
        path: "{{ nginx_conf_file }}"
        state: absent
      when: nginx_conf_stat.stat.isdir is defined and nginx_conf_stat.stat.isdir

    - name: Create nginx.conf if not exists
      copy:
        dest: "{{ nginx_conf_file }}"
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                      autoindex on;  # Agregado para permitir el listado del directorio
                  }

                  location / {
                      return 301 https://$host$request_uri;
                  }
              }

              server {
                  listen 443 ssl;
                  server_name interconectados.duckdns.org;

                  ssl_certificate /etc/letsencrypt/live/interconectados.duckdns.org/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/interconectados.duckdns.org/privkey.pem;

                  location / {
                      proxy_pass http://front-interconectados-vite-app-1:3000;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                  }
              }
          }
      when: not nginx_conf_stat.stat.exists

    - name: Create nginx.temp.conf
      copy:
        dest: "{{ nginx_temp_conf_file }}"
        content: |
          events {
              worker_connections 1024;
          }

          http {
              server {
                  listen 80;
                  server_name interconectados.duckdns.org;

                  location /.well-known/acme-challenge/ {
                      root /var/www/certbot;
                      autoindex on;  # Agregado para permitir el listado del directorio
                  }

                  location / {
                      return 200 'Temporary Nginx Server';
                  }
              }
          }

    - name: Create test file for Certbot validation
      copy:
        dest: "{{ challenge_dir }}/test.txt"
        content: "test"

    - name: Check if Dockerfile.certbot exists
      stat:
        path: "{{ dockerfile_certbot }}"
      register: dockerfile_certbot_stat

    - name: Move Dockerfile.certbot to correct location if not found
      copy:
        src: /opt/interconectados/front-interconectados-vite/Dockerfile.certbot
        dest: "{{ dockerfile_certbot }}"
      when: not dockerfile_certbot_stat.stat.exists

    - name: Build Certbot Docker image
      command: docker build -f Dockerfile.certbot -t front-interconectados-vite_certbot .
      args:
        chdir: "{{ workdir }}"

    - name: Start Docker Compose with temporary Nginx configuration
      command: docker-compose -f "{{ docker_compose_file }}" up -d

    - name: Wait for services to start
      pause:
        seconds: 10

    - name: Verify test file in Nginx container
      command: docker exec front-interconectados-vite-nginx-1 ls /var/www/certbot/.well-known/acme-challenge/test.txt

    - name: Run Certbot to obtain SSL certificates
      command: docker-compose run certbot certonly --webroot -w /var/www/certbot -m interconectados.sa@gmail.com --agree-tos --no-eff-email -d interconectados.duckdns.org --force-renewal
      async: 180
      poll: 0
      register: certbot_result

    - name: Debug Certbot Result
      debug:
        var: certbot_result

    - name: Wait for Certbot to complete
      async_status:
        jid: "{{ certbot_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 3
      delay: 10

    - name: Stop all Docker containers
      command: docker-compose down
      when: job_result.finished

    - name: Update nginx.conf
      copy:
        src: "{{ nginx_temp_conf_file }}"
        dest: "{{ nginx_conf_file }}"
      when: job_result.finished

    - name: Restart Docker Compose with final Nginx configuration
      command: docker-compose up -d
      when: job_result.finished
